MsMekanik/Models/Siparis.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MsMekanik.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Siparis
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Siparis()
        {
            this.IsEmriEnvanteri = new HashSet<IsEmriEnvanteri>();
            this.SiparisUrun = new HashSet<SiparisUrun>();
        }
    
        public int ID { get; set; }
        public Nullable<int> MusteriID { get; set; }
        public Nullable<int> UrunID { get; set; }
        public Nullable<System.DateTime> SiparisTarihi { get; set; }
        public string FirmaAdi { get; set; }
        public string YetkiliAdi { get; set; }
        public Nullable<bool> Konu { get; set; }
        public Nullable<System.DateTime> TerminBaslangic { get; set; }
        public Nullable<System.DateTime> TerminBitis { get; set; }
        public string Tel { get; set; }
        public Nullable<int> OnaylayanID { get; set; }
    
        public virtual Calisan Calisan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IsEmriEnvanteri> IsEmriEnvanteri { get; set; }
        public virtual Musteri Musteri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SiparisUrun> SiparisUrun { get; set; }
    }
}

MsMekanik/Controllers/SiparisController.cs
using MsMekanik.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace MsMekanik.Controllers
{
    
    public class SiparisController : Controller
    {
        msmekani_veriEntities baglanti = new msmekani_veriEntities();

        public ActionResult Index()
        {
            SiparisUrunList model = new SiparisUrunList();

            List<Urunler> urunList = baglanti.Urunler.OrderBy(x => x.UrunKodu).ToList();
            model.SiparisUrunListi = (from s in urunList
                                      select new SelectListItem
                                      {
                                          Text = s.UrunKodu,
                                          Value = s.ID.ToString()
                                      }).ToList();
            model.SiparisUrunListi.Insert(0, new SelectListItem { Value = "", Text = "Seçiniz", Selected = true });
            List<SiparisUrun> _SiparisList = new List<SiparisUrun>();
            var _model = new Siparis();
            for (int i = 0; i < 6; i++)
            {
                _model.SiparisUrun.Add(new SiparisUrun());
            }
            ViewBag.Urunler = new SelectList(baglanti.Urunler.ToList(), "ID", "UrunAdi");
            return View(_model);
        }

        [HttpPost]
        public ActionResult Index(Siparis data)
        {
            //todo : helperlar strongly type olmayacak
            if(data != null)
            {
                Siparis db_siparis = new Models.Siparis()
                {
                    TerminBaslangic=data.TerminBaslangic,
                    TerminBitis=data.TerminBitis,
                    Konu=data.Konu,
                    YetkiliAdi=data.YetkiliAdi,
                    FirmaAdi=data.FirmaAdi
                };
                foreach (var item in data.SiparisUrun)
                {
                    db_siparis.SiparisUrun.Add(new SiparisUrun()
                    {
                        Siparis=db_siparis,
                        Urunler=baglanti.Urunler.Find(item.Urunler.ID)
                    });
                }
                baglanti.Siparis.Add(db_siparis);
                baglanti.SaveChanges();   
            }


            //SiparisUrun siparisEkle = new SiparisUrun();


            //siparisEkle.Siparis.MusteriID = 1;

            //if (form["UrunKodu1"] != "" && form["UrunAdi1"] != "" && form["Adet1"] != "" && form["Malzeme1"] != "" && form["GerekliMalzeme1"] != "")
            //{
            //    siparisEkle.UrunID = Convert.ToInt32(form["UrunKodu1"]);
            //    siparisEkle.UrunID = 1;
            //    siparisEkle.Adedi= Convert.ToInt32(form["Adet1"]);
            //    siparisEkle.MalzemeMiktari= Convert.ToInt32(form["Malzeme1"]);
            //    baglanti.SiparisUrun.Add(siparisEkle);
            //    baglanti.SaveChanges();
            //}

            ViewBag.Urunler = new SelectList(baglanti.Urunler.ToList(), "ID", "UrunAdi");
            return View();
        }
        [HttpPost]
        public ActionResult AdiMalzemeListele(int id)
        {
            //List<Urunler> UrunlerListe = baglanti.Urunler.Where(x => x.ID == id).OrderBy(x => x.UrunAdi).ToList();

            //ViewBag.UrunList = new SelectList(UrunlerListe.ToList(), "ID", "UrunAdi");
            //List<SelectListItem> itemList = (from i in UrunlerListe
            //                                select new SelectListItem
            //                                {
            //                                    Value = i.ID.ToString(),
            //                                    Text=i.UrunAdi

            //                                }).ToList();
            
            var urun = baglanti.Urunler.FirstOrDefault(x => x.ID == id);
            
            return PartialView("_SecilenUrun",urun);
        }
    }
}

MsMekanik/Views/Siparis/Index.cshtml
@model MsMekanik.Models.Siparis
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
    int i = 0;
}

<h2>Sipariş </h2>

@*<form id="form1" name="form1" method="post" action="~/Siparis/Index">*@
    @Html.BeginForm("Index","Siparis",FormMethod.Post)
    {
    <table width="800" height="571" border="1" align="center" cellspacing="0">
        <tr>
            <td width="1021" height="113">
                <table width="100%" border="1" cellspacing="0" height="100%">
                    <tr>
                        <td width="17%" rowspan="5">Logo</td>
                        <td width="42%" rowspan="5" align="center"><h2><strong>SİPARİŞ FORMU - ORDER</strong> FORM</h2></td>
                        <td width="23%">DÖK. NO</td>
                        <td width="18%">FR.08.01</td>
                    </tr>
                    <tr>
                        <td>YAYIN TARİHİ</td>
                        <td>&nbsp;</td>
                    </tr>
                    <tr>
                        <td>REVİZYON NO</td>
                        <td>&nbsp;</td>
                    </tr>
                    <tr>
                        <td>REVİZYON TARİHİ</td>
                        <td>&nbsp;</td>
                    </tr>
                    <tr>
                        <td>SAYFA NO</td>
                        <td align="center">1/1</td>
                    </tr>
                </table>
            </td>
        </tr>
        <tr>
            <td height="121">
                <table width="100%" border="1" cellspacing="0">
                    <tr>
                        <td width="28%" height="23"><strong>TARİH / DATE</strong></td>
                        <td width="35%" height="23"><input type="text" width="274" name="Tarih" id="Tarih" /></td>
                        <td width="15%"><strong>TEL(PHONE)/FAX</strong></td>
                        <td width="22%" height="23"><input type="text" width="171" name="Tel" id="Tel" /></td>
                    </tr>
                    <tr>
                        <td height="23"><strong>FİRMA /CONPANY</strong></td>
                        <td height="23"><input type="text" width="274" name="Firma" id="Firma" /></td>
                        <td><strong>SİPARİŞ/ORDER NO</strong></td>
                        <td height="23"><input type="text" width="171" name="SiparisNo" id="SiparisNo" /></td>
                    </tr>
                    <tr>
                        <td height="23"><strong>YETKİLİ / RESPECTİVE PERSON</strong></td>
                        <td height="23" colspan="3"><input type="text" width="300" name="Yetkili" id="Yetkili" /></td>
                    </tr>
                    <tr>
                        <td height="23"><strong>KONU /TOPIC</strong></td>
                        <td height="23" colspan="3"><input type="text" width="300" name="Konu" id="Konu" /></td>
                    </tr>
                    <tr>
                        <td height="23"><strong>TERMİN / DEADLİNE</strong></td>
                        <td height="23" colspan="3"><input type="text" width="300" name="Termin" id="Termin" /></td>
                    </tr>
                </table>
                <table width="100%" border="1" cellspacing="0">
                    <tr>
                        <td width="3%" align="center">NO</td>
                        <td width="13%" align="center">ÜRÜN KODU / UNIT CODE</td>
                        <td width="36%" align="center">ÜRÜN ADI VEYA CİNSİ /PRODUCT TYPE</td>
                        <td width="11%" align="center">ADET / QUANTITY</td>
                        <td width="15%" align="center">MALZEME / MATERIAL</td>
                        <td width="22%" align="center">GEREKLİ MALZEME MİKTARİ / REQUIRED MATERIAL QUANTITY</td>
                    </tr>
                    @foreach(var siparisurun in Model.SiparisUrun)
                    { 
                    <tr>
                        <td>1</td>
                        <td>
                           @Html.DropDownListFor(modelItem=> siparisurun.Urunler.ID, (SelectList)(ViewBag.Urunler as SelectList),"Seçiniz",new {@id=$"urunlerddl_{i}",@class="urunlerddl" })
                        </td>
                        <td id="urun_@i">                       
                        </td>
                        <td><input type="text" width="74" name="Adet1" id="Adet1" /></td>
                        <td>@*@Html.DropDownListFor(m => m.UrunMalzemeID, Model.SiparisMalzemeListi)*@</td>
                        <td><input type="text" width="157" name="GerekliMalzeme1" id="GerekliMalzeme1" /></td>
                    </tr>
                    @(i++)
                    }
                    <tr>
                        <td>2</td>
                        <td>
                            <input type="text" name="UrunKodu2" id="UrunKodu2" />
                        </td>
                        <td>
                            <input type="text" width="271" name="UrunAdi2" id="UrunAdi2" />
                        </td>
                        <td><input type="text" width="74" name="Adet2" id="Adet2" /></td>
                        <td><input type="text" width="104" name="Malzeme2" id="Malzeme2" /></td>
                        <td><input type="text" width="157" name="GerekliMalzeme2" id="GerekliMalzeme2" /></td>
                    </tr>
                    <tr>
                        <td>3</td>
                        <td>
                            <input type="text" name="UrunKodu3" id="UrunKodu3" />
                        </td>
                        <td>
                            <input type="text" width="271" name="UrunAdi3" id="UrunAdi3" />
                        </td>
                        <td><input type="text" width="74" name="Adet3" id="Adet3" /></td>
                        <td><input type="text" width="104" name="Malzeme3" id="Malzeme3" /></td>
                        <td><input type="text" width="157" name="GerekliMalzeme3" id="GerekliMalzeme3" /></td>
                    </tr>
                    <tr>
                        <td>4</td>
                        <td>
                            <input type="text" name="UrunKodu4" id="UrunKodu4" />
                        </td>
                        <td>
                            <input type="text" width="271" name="UrunAdi4" id="UrunAdi4" />
                        </td>
                        <td><input type="text" width="74" name="Adet4" id="Adet4" /></td>
                        <td><input type="text" width="104" name="Malzeme4" id="Malzeme4" /></td>
                        <td><input type="text" width="157" name="GerekliMalzeme4" id="GerekliMalzeme4" /></td>
                    </tr>
                    <tr>
                        <td>5</td>
                        <td>
                            <input type="text" name="UrunKodu5" id="UrunKodu5" />
                        </td>
                        <td>
                            <input type="text" width="271" name="UrunAdi5" id="UrunAdi5" />
                        </td>
                        <td><input type="text" width="74" name="Adet5" id="Adet5" /></td>
                        <td><input type="text" width="104" name="Malzeme5" id="Malzeme5" /></td>
                        <td><input type="text" width="157" name="GerekliMalzeme5" id="GerekliMalzeme5" /></td>
                    </tr>
                    <tr>
                        <td>6</td>
                        <td>
                            <input type="text" name="UrunKodu6" id="UrunKodu6" />
                        </td>
                        <td>
                            <input type="text" width="271" name="UrunAdi6" id="UrunAdi6" />
                        </td>
                        <td><input type="text" width="74" name="Adet6" id="Adet6" /></td>
                        <td><input type="text" width="104" name="Malzeme6" id="Malzeme6" /></td>
                        <td><input type="text" width="157" name="GerekliMalzeme6" id="GerekliMalzeme6" /></td>
                    </tr>
                    <tr>
                        <td colspan="5">&nbsp;</td>
                        <td>&nbsp;</td>
                    </tr>
                    <tr>
                        <td colspan="5">&nbsp;</td>
                        <td>&nbsp;</td>
                    </tr>
                    <tr>
                        <td colspan="5">&nbsp;</td>
                        <td>&nbsp;</td>
                    </tr>
                    <tr>
                        <td height="90" colspan="3" valign="top"><strong>MEKANİK SANATLAR ONAYI/MEKANİK SANATLAR CONFIRMATION</strong></td>
                        <td colspan="3">&nbsp;</td>
                    </tr>
                </table>
                <input type="text" width="271" name="UrunAdi5" id="UrunAdi5" />
            </td>
        </tr>
        <tr>
            <td height="19">
                <table width="100%" border="0">
                    <tr>
                        <td align="center" valign="middle"><input type="submit" name="Gonder" id="Gonder" value="Gönder" /></td>
                        <td align="center" valign="middle"><input type="submit" name="Yazdir" id="Yazdir" value="Yazdır" /></td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>
    }
@*</form>*@
@section scripts
{
    <script type="text/javascript">
        function ajaxFonk(id,index){
            $.ajax({
                url: '/Siparis/AdiMalzemeListele',
                type: 'POST',
                dataType: 'HTML',
                data: { 'id': id },
                success: function (data) {
                    //$.each(data, function (index, option) {
                    //    adilist.append('<option value=' + option.Value + '>' + option.Text + '</option');
                    //});
                    $("#urun_" + index).html(data);
                    
                }

            });
        }

        $(document).ready(function () {
            $(".urunlerddl").change(function () {
                var id = $(this).val();
                console.log('id:', id);
                var index = $(this).attr('id').split('_')[1];
                console.log('index:', index);

                ajaxFonk(id, index);
            });
        });
    </script>
    }